apiVersion: v1
kind: Secret
metadata:
  name: {{ include "100things.fullname" . }}-postgresql
  labels:
    {{- include "100things.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.postgresql.auth.password | b64enc }} 