# Default values for 100things
replicaCount: 1

image:
  repository: ghcr.io/jfairbairn/100things  # Using GitHub Container Registry with correct username
  tag: latest
  pullPolicy: IfNotPresent
  # For production, you might want to use a specific tag instead of 'latest'
  # tag: v1.0.0
  # pullPolicy: Always
  # For local development
  # repository: localhost/100things
  # pullPolicy: IfNotPresent
  # For production, you would use something like:
  # repository: your-registry.com/100things
  # pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# PostgreSQL configuration
postgresql:
  enabled: true
  auth:
    username: 100things
    database: 100things
    # You can set this directly in values.yaml for development
    # For production, use --set postgresql.auth.password=<password> or a separate values file
    password: "your-secure-password-here"
    secretName: "{{ include \"100things.fullname\" . }}-postgresql"
  primary:
    persistence:
      enabled: true
      size: 10Gi
      storageClass: "longhorn"
      accessModes:
        - ReadWriteOnce  # PostgreSQL primary needs RWO access
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 512Mi

# Application configuration
app:
  env:
    - name: DATABASE_URL
      valueFrom:
        secretKeyRef:
          name: {{ include "100things.fullname" . }}-postgresql
          key: postgres-password
    - name: NODE_ENV
      value: "production" 